name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  nb_utils: ^4.4.13
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  cached_network_image: ^3.2.0
  google_fonts: 2.3.1
  flutter_vector_icons: ^1.0.0
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.1
  date_time_picker: 2.1.0
  url_launcher: ^6.0.18
  flutter_rating_bar: ^4.0.0
  package_info: ^2.0.2
  flutter_remix: ^0.0.3
  dotted_border: 2.0.0+2
  flutter_custom_tabs: ^1.0.4

  #image:
  path_provider: ^2.0.8
  image_picker: ^0.8.4+5
  multi_image_picker: ^4.8.1
  photo_view: ^0.13.0
  file_picker: ^4.3.3

  # PAYMENTS
  flutter_stripe: ^2.2.0
  razorpay_flutter: ^1.2.9
  flutterwave_standard: 1.0.3

  #notifications:
  onesignal_flutter: ^3.2.8

  #chart
  syncfusion_flutter_charts: ^19.4.48
  charts_flutter: ^0.12.0

  #map:
  geocoding: ^2.0.1

  #Firebase
  firebase_crashlytics: ^2.4.5
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  firebase_database: ^9.0.5
  paginate_firestore: ^1.0.3
  cloud_firestore: ^3.1.6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flag/
    - images/app_images/
    - images/setting_icon/
    - images/setting_icon/
