name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 4.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  nb_utils: ^4.4.17
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5
  cached_network_image: ^3.2.0
  google_fonts: ^2.3.2
  flutter_vector_icons: ^1.0.0
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.6.1
  date_time_picker: 2.1.0
  url_launcher: ^6.1.0
  flutter_rating_bar: ^4.0.0
  package_info: ^2.0.2
  flutter_remix: ^0.0.3
  dotted_border: 2.0.0+2
  flutter_custom_tabs: ^1.0.4

  #image:
  path_provider: ^2.0.9
  image_picker: ^0.8.5
  multi_image_picker: ^4.8.1
  photo_view: ^0.13.0
  file_picker: ^4.5.1

  # PAYMENTS
  flutter_stripe: ^2.5.0
  razorpay_flutter: ^1.3.0
  flutterwave_standard: 1.0.3

  #notifications:
  onesignal_flutter: ^3.3.0

  #chart
  syncfusion_flutter_charts: ^20.1.51
  charts_flutter: ^0.12.0

  #map:
  geocoding: ^2.0.4

  #Firebase
  firebase_crashlytics: ^2.6.3
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  firebase_storage: ^10.2.14
  firebase_database: ^9.0.12
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^3.1.13

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  mobx_codegen: ^2.0.6
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flag/
    - images/app_images/
    - images/setting_icon/
    - images/setting_icon/
